### ISSUE TITLE
File Interaction

### ISSUE THREAD

**Issue by shortstuffsushi** [incrediblesound/DiamondDB#2]
Hi there,

Google Now suggested your repo for some reason. I thought it was neat, so I took a look. Still think it's an interesting idea, but I think you're going to kill your performance and make this a non starter by having every interaction involve the file system. I recommend keeping as much in memory as possible for immediate availability of data, or at least having some sort of in memory cache for frequently accessed items. You know, database optimization and such. Additionally, you'll probably want to avoid writing out to disk constantly. Batching will save you some work there. 

At any rate, that's my two cents after thirty seconds of review. It's a cool idea and certainly a good exercise. Best of luck with your work.

**Comment by incrediblesound** [comment]
Awesome, thanks for the advice! It sounds like what I should do is:
1. add a cache layer to minimize reading from the file system
2. add a batching mechanism to minimize writing to the file system

sound about right?

**Comment by shortstuffsushi** [comment]
Yes, I think those are a good couple of items to start with. In addition, you may want to look into adding the ability to query by alternative fields (besides ID), indexing to make that more performance, and ensuring your DB is [ACID Compliant](https://en.m.wikipedia.org/wiki/ACID). You can expand as far as you want depending on how serious you are about making a full featured DB.

**Comment by keithchilders** [comment]
If you're going to take this further, I'd also recommend a pluggable persistence layer so if I want, I can extend your base connector to write my own persistence module (say I like your api and client library better than working with native, but I would rather persist the bits to Amazon S3 or mongodb or ???). If you're going to do a caching layer, make that pluggable too, so connectors can be written for redis, etc.

**Comment by incrediblesound** [comment]
I like the idea of making things modular and configurable!

**Comment by incrediblesound** [comment]
OK so I pretty much re-wrote the whole thing to have a persistence module and a cache module that are decoupled from the main API. They communicate using a standard system of messages which allows people to write their own modules for interfacing with other persistence types and caches. Thanks for the great ideas folks.

**Comment by shortstuffsushi** [comment]
Awesome, keep up the good work 👍
